<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  ' by ' => ', ',
  '<a href="{url}" title="About us | odesys">What we do</a>.' => '<a href="{url}" title="O nas | odesys">Kaj počnemo</a>.',
  '<a href="{url}" title="Contact us | odesys">Who we are</a>' => '<a href="{url}" title="Kontaktirajte nas | odesys">Kdo smo</a>',
  '<a href="{url}" title="Article | A different approach to decision making">A different approach to decision making</a> by Taj Pelc' => '<a href="{url}" title="Article | A different approach to decision making">A different approach to decision making</a>, Taj Pelc',
  '<a href="{url}" title="Article | Learning from our mistakes">Learning from our mistakes</a> by Frenk T. Sedmak Nahtigal' => '<a href="{url}" title="Article | Learning from our mistakes">Learning from our mistakes</a>, Frenk T. Sedmak Nahtigal',
  '<a href="{url}" title="Blog | odesys">Our blog</a>' => '<a href="{url}" title="Blog | odesys">Naš blog</a>' ,
  '<a href="{url}" title="begin your journey" class="decisionNew" rel="nofollow">begin your journey</a>' => '<a href="{url}" title="začni svoje potovanje" class="decisionNew" rel="nofollow">začni svoje potovanje</a>',
  '<a href="{url}" title="begin your journey" class="decisionNew">begin your journey</a>' => '<a href="{url}" title="začni svoje potovanje" class="decisionNew">začni svoje potovanje</a>',
  'By combining our knowledge of decision theory with our skills of web development, we would like to create a world where the quality of our decisions and the quality of life are at their best.' => 'Z združitvijo znanja teorije odločanja in razvoja spletnih tehnologij, želimo ustvariti svet v katerem sta tako kakovost naših odločitev, kot tudi življenja na vrhuncu.',
  'By inviting other people to look at your decision from an independent or unbiased point of view through the power of social networking, you can increase your insight into the decision problem.' => 'Povečanje vpogleda v vašo odločitev lahko dosežete z deljenjem odločitvenega modela s svojimi prijatelji, ki lahko nanjo pogledajo z drugačnega zornega kota. Izkoristite moč družabnih omrežij.',
  'Decision making is hard. We know. Why not let our system guide you through the process step by step until you have reached a decision?' => 'Odločanje je težavno. Vemo. Naj vas naš sistem vodi čez odločitveni proces, dokler ne pridete do odločitve.',
  'If you would like to work with us or have a question, we encourage you to <a href="{url}" title="contact us">get in touch</a>.' => 'Če imate vprašanje, pripombo, predlog ali pa bi želeli sodelovati z nami, nas <a href="{url}" title="contact us">kontaktirajte</a>.',
  'If you would like, you can remain anonymous, keep your decision private and just use our tool to model the decision problem for yourself.' => 'Odesys lahko uporabljate anonimno brez prijave. Lahko izbirate med javno in zasebno odločitvijo, kjer samo vi vidite vaš model.',
  'Latest public decisions by our users' => 'Zadnje javne odločitve naših uporabnikov',
  'Odesys is a web-based decision support system that augments the user\'s decision-making process.' => 'Odesys je spletni sistem za podporo odločanju, ki pomaga uporabniku pri odločitvenem procesu',
  'We are always looking for new connections.' => 'Vedno iščemo nove povezave.',
  'We are decision theory researches and explorers of the human mind.' => 'Smo raziskovalci na področju teorije odločanja in človeškega uma.',
  'We provide the tool that help you quickly and easily build a model of your decision problem by guiding you through the decision-making process step-by-step.' => 'Nudimo orodje s katerim lahko hitro in preprosto zgradite model svoje odločitve. Sistem vas vodi skozi odločitveni proces korak za korakom.',
  'odesys // helping you decide' => 'odesys // pomaga pri odločanju',
);