<?php $this->pageTitle='ODESYS: Terms of use'; ?>

<div id="heading">
    <h2>Disclaimer</h2>
</div>
<div id="content">
    <p>Welcome to Odesys, decision-support application service. Your use of this service is subject to these Terms of Use and Privacy Policy:</p>
    <h2>TERMS OF USE</h2>
    <ul>
        <li>ODESYS is only a tool, you need to analize your decisions. You are the one that decides, and ODESYS and its owners are not responsible for the consequences of your decisions.</li>
        <li>ODESYS reserves the right to change or modify entire application without prior notice to you or your acceptance to these changes.</li>
        <li>ODESYS is a Web-based Decision Support System and is offered on "as is" and "as available" basis.</li>
        <li>You solely take all responsibility for the content that you generate using this system.</li>
        <li>ODESYS or its owners do not control the content made using this system. As such, we nor any third parties provide any warranty or guarantee as to the quality, integrity, accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</li>
        <li>Your use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products, services or information available through this website meet your specific requirements.</li>
        <li>ODESYS contains material which is owned by or licensed to its owners. This material includes, but is not limited to, the design, layout, look, appearance and graphics, source code. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions.</li>
        <li>ODESYS is offered free of charge or obligation.</li>
        <li>ODESYS does not claim ownership rights to any content generated by its users.</li>
        <li>Unauthorised use of this service may give rise to a claim for damages and/or be a criminal offence.</li>
        <li>ODESYS uses cookies to monitor browsing preferences. You need to allow cookies to be used in order to use this service.</li>
        <li>If you violate any of these Terms of Use or any laws, ODESYS owners have the right to immediatelly remove such content and remove your account from the system.</li>
    </ul>
    <h2>PRIVACY POLICY</h2>
    <p>This privacy policy sets out how ODESYS uses and protects any information that you give to ODESYS when you use this service.</p>
    <p>ODESYS is committed to ensuring that your privacy is protected. Should we ask you to provide certain information by which you can be identified when using this website, then you can be assured that it will only be used in accordance with this privacy statement.</p>
    <p>ODESYS may change this policy from time to time by updating this page. You should check this page from time to time to ensure that you are happy with any changes. This policy is effective from 1st of September, 2011.</p>
    <h3>What we do with the information we gather</h3>
    <p>We use Facebook OpenAuth 2.0 for loging you into the service and ODESYS stores only the basic (public) information gathered from Facebook.</p>
    <p>We require this information to understand your needs and provide you with a better service, and in particular for the following reasons:</p>
    <ul>
        <li>Internal record keeping.</li>
        <li>Bringing you better experience using this service.</li>
        <li>We may use the information to improve this service.</li>
    </ul>
    <h3>Security</h3>
    <p>We are committed to ensuring that your information is secure. In order to prevent unauthorised access or disclosure, we have put in place suitable physical, electronic and managerial procedures to safeguard and secure the information we collect online. </p>
    <h3>How we use cookies</h3>
    <ul>
        <li>A cookie is a small file which asks permission to be placed on your computer's hard drive. Once you agree, the file is added and the cookie helps analyse web traffic or lets you know when you visit a particular site. Cookies allow web applications to respond to you as an individual. The web application can tailor its operations to your needs, likes and dislikes by gathering and remembering information about your preferences.</li>
        <li>We use traffic log cookies to identify which pages are being used. This helps ODESYS analyse data about web page traffic and improve our service in order to tailor it to user needs. We only use this information for statistical analysis purposes and then the data is removed from the system.</li>
        <li>Overall, cookies help us provide you with a better website, by enabling us to monitor which pages you find useful and which you do not. A cookie in no way gives us access to your computer or any information about you, other than the data you choose to share with us.</li>
        <li>You can choose to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. This will prevent you from taking the advantage of using this service.</li>
    </ul>
    <h3>Controlling your personal information</h3>
    <p>ODESYS or its owners will not sell, distribute or lease your personal information to third parties unless we have your permission or are required by law to do so.</p>
    <p>If you believe that any information we are holding on you is incorrect or incomplete, please write to or email us as soon as possible, at the above address. We will promptly correct any information found to be incorrect.</p>
</div>